### PR TITLE
Use stylesheet for css

### PR DESCRIPTION
**Pull request by Shluffy**

### CODE REVIEW

**Comment by Shluffy** [comment]
@gosoccerboy5 I am also going to work on automatically updating the image

**Comment by Shluffy** [comment]
> @gosoccerboy5 I am also going to work on automatically updating the image

well, it does that if you open to `/?url=`

**Comment by gosoccerboy5** [comment]
Um, I don't need a stylesheet, but thank you..

**Comment by Shluffy** [comment]
@gosoccerboy5 are you going to be using a stylesheet? It won't be needed unless you end up with multiple pages

**Comment by gosoccerboy5** [comment]
I mean who knows, I may end up expanding it the repo

**Comment by gosoccerboy5** [comment]
ok time to merge

**Pull request merged**
