### PR TITLE
Add backwords compatibility

### PR DESCRIPTION
**Pull request by Samq64**
Adds backwards compatibility to my previous PR and a couple of other minor changes.

(Sorry for not doing this before.)

Tested locally, briefly.

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
Thanks, I was just thinking about that. Could you fix the indentation here? (click the link) https://github.com/gosoccerboy5/view-images/blob/6e03949595f5e8a0caece2ee0360d913b38a4ae4/index.html#L53-L58 It looks like you're mixing tabs and spaces and it looks weird. By the way, I'm busy so have you tested this?

**Comment by Samq64** [comment]
I copied and pasted that bit of code, that's why the indentation is different.

**Comment by gosoccerboy5** [comment]
I think that commit should do the trick

**Comment by Samq64** [comment]
> 
> 
> I think that commit should do the trick

Thanks. it did the commit in the online editor which indents in wed ways.

**Comment by gosoccerboy5** [comment]
ok, looks good to me(rge)

**Pull request merged**
